analytic_description: test
analytic_id: 100
analytic_name: test
data_source:
  name: 'key3p_data'  # Use the name you defined
  required_fields:
    - 'Audit Entity ID'
    - 'Audit Entity Name'
    - 'Audit Leader'
    - 'PRIMARY TLM THIRD PARTY ENGAGEMENT'
    - 'Third Party Inherent Risk'
    - 'Helper-KPA Contains Key TLM Third Party'
reference_data:
  Risk_Categories: {}
reporting:
  detail_required: true
  group_by: Audit Leader
  summary_fields:
  - GC
  - PC
  - DNC
  - Total
  - DNC_Percentage
thresholds:
  error_percentage: 5.0
  rationale: Risk assessments require higher accuracy due to regulatory requirements.
validations:
- description: Risk rating must be assigned for entities with third parties
  parameters:
    risk_level_field: Vendor Risk Rating
    third_party_field: Third Party Vendors
  rule: third_party_risk_validation
- description: Risk rating must be a valid value
  parameters:
    field_name: Vendor Risk Rating
    valid_values:
    - Critical
    - High
    - Medium
    - Low
    - Not Applicable
  rule: enumeration_validation
