analytic_description: Validates workpaper review process for proper segregation of duties and appropriate approval sequences
analytic_id: 99
analytic_name: Audit Workpaper Review Validation
data_source:
  name: audit_workpapers_2025q2  # This should match your YAML data source name
  required_fields:
    - Workpaper_ID
    - Audit_Entity
    - Submitter
    - Reviewer
    - Approver
    - Submission_Date
    - Review_Date
    - Approval_Date
    - Status
    - Risk_Level
    - Comments
reporting:
  detail_required: true
  group_by: Audit_Entity
  summary_fields:
  - GC
  - PC
  - DNC
  - Total
  - DNC_Percentage
thresholds:
  error_percentage: 10.0  # You specified 10% in the prompt
  rationale: Maximum allowed error rate for this validation
validations:
- description: Validates proper review process, segregation of duties, and documentation for high-risk workpapers
  parameters:
    original_formula: "Submitter <> Reviewer AND Reviewer <> Approver AND Submission_Date <= Review_Date AND Review_Date <= Approval_Date AND ((Risk_Level = \"High\" OR Risk_Level = \"Critical\") AND Status = \"Complete\" => NOT ISBLANK(Comments))"
    formula: "(df['Submitter'] != df['Reviewer']) & (df['Reviewer'] != df['Approver']) & (df['Submission_Date'] <= df['Review_Date']) & (df['Review_Date'] <= df['Approval_Date']) & (~((df['Risk_Level'].isin(['High', 'Critical'])) & (df['Status'] == 'Complete')) | ~pd.isna(df['Comments']))"
  rule: custom_formula